# Generated by Django 3.0.5 on 2020-04-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200414_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slugr',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
