# Generated by Django 3.0.5 on 2020-04-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slugr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slugr',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
